name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend Service
        run: |
          echo "Triggering backend deploy..."
          curl -s -o /dev/null -w "%{http_code}" -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}

      - name: Deploy Frontend Service
        run: |
          echo "Triggering frontend deploy..."
          curl -s -o /dev/null -w "%{http_code}" -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}
